### ISSUE TITLE
Regressions in Rx.ReactiveTest since 2.3.22

### ISSUE THREAD

**Issue by andrewk** [Reactive-Extensions/RxJS#582]
I have prepared a test case demonstrating the two problems I wish to report.
https://github.com/andrewk/rxjs-testing-regression

Firstly, the merge test in test/regression.js fails as of 2.3.23 and 2.3.24 but passes in 2.3.22.
Using the `collectionAssert` matcher from the docs, the following error is produced:
```
AssertionError: Expected: [OnNext(foo)@100,OnNext(bar)@150]
Actual: [OnNext(foo)@100,OnNext(bar)@150]
```
Secondly, as of 2.3.25, `Rx.ReactiveTest` is no longer a property of the resulting object when loading `require('rx')`
```
/Users/andrew/Projects/personal/rxjs-testing-regression/test/regression.js:30
var onNext = Rx.ReactiveTest.onNext,
                            ^
TypeError: Cannot read property 'onNext' of undefined
    at Object.<anonymous>
```
A `console.log` of the Rx object of 2.3.25 in Node (0.10, 0.11, 0.12, and iojs 1.0) confirms this.

All versions tested in Travis-CI:
  - [RxJS 2.3.22 - PASS](https://travis-ci.org/andrewk/rxjs-testing-regression/builds/50028412)
  - [RxJS 2.3.23 - FAIL](https://travis-ci.org/andrewk/rxjs-testing-regression/builds/50028416)
  - [RxJS 2.3.24 - FAIL](https://travis-ci.org/andrewk/rxjs-testing-regression/builds/50028434)
  - [RxJS 2.3.25 - FAIL](https://travis-ci.org/andrewk/rxjs-testing-regression/builds/50028469)

I apologise that this report doesn't include a PR, this is my first time using RxJS and I don't know my way around yet. Thanks :)

**Comment by mattpodwysocki** [comment]
@andrewk someone changed it to `rx.all` and not sure when but that has been fixed.

**Comment by andrewk** [comment]
@mattpodwysocki Please consider re-opening this issue, as the problem introduced in 2.3.23 (and now present in master) hasn't been addressed.

Specifically, the assertEquals assertion function from [docs/gettingstarted/testing.md](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/gettingstarted/testing.md) no longer produces sensible results for merged observables. ( [spec demonstrating such](https://github.com/andrewk/rxjs-testing-regression/blob/master/test/regression.js#L96) )

While 2.3.22 passes as expected, 2.3.23, 2.3.24 and master produce the following:
```
AssertionError: Expected: [OnNext(foo)@100,OnNext(bar)@150]
Actual: [OnNext(foo)@100,OnNext(bar)@150]
```

As you can see, the assertion should pass. I believe something in `Rx.internals.isEqual` has changed to cause false negatives.

**Comment by mattpodwysocki** [comment]
@andrewk these lines are incorrect:
https://github.com/andrewk/rxjs-testing-regression/blob/master/test/regression.js#L103-L106

It should be the following.  Not sure why you have it as an array inside, because the values are not arrays:
```js
 collectionAssert.assertEqual(results.messages, [
onNext(100, 'foo'),
onNext(150, 'bar'),
]); 
```

Here is a minimal reproduction which works as expected:
```js
var Rx = require('rx');

var TestScheduler = Rx.TestScheduler,
    onNext = Rx.ReactiveTest.onNext,
    onError = Rx.ReactiveTest.onError,
    onCompleted = Rx.ReactiveTest.onCompleted,
    subscribe = Rx.ReactiveTest.subscribe;

var scheduler = new TestScheduler();

stream1 = scheduler.createHotObservable(
  onNext(100, 'foo'),
  onCompleted(500)
);

stream2 = scheduler.createHotObservable(
  onNext(150, 'bar'),
  onCompleted(500)
);

var results = scheduler.startWithTiming(
  function () {
    return stream1.merge(stream2);
  },
  50,
  90,
  300
);

console.log(JSON.stringify(results.messages));
```

Output:
```bash
λ node ..\foo.js
[
  {"time":100,"value":{"hasValue":true,"kind":"N","value":"foo"}},
  {"time":150,"value":{"hasValue":true,"kind":"N","value":"bar"}}
]
```

As you will notice, there is no array here, so if it failed in previous builds then that means my `equals` was incorrect, and there is no regression here.

**Comment by andrewk** [comment]
Wonderful, I'm glad it was my PEBKAC! Thanks for clarifying, apologies for
wasting your time.

**Comment by mattpodwysocki** [comment]
@andrewk no worries!  It was a regression in `isEqual` that we fixed in that mean time.

**Comment by jwoodhull** [comment]
Still seeing TypeError: Cannot read property 'onNext' of undefined in karma when building with webpack.  It looks like the RequireJs code is not quite correct.
